name: Deploy feature
on: 
  push: 
    branches: 
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: cfst-3457-1683623b4befe10bf2bb969c4-nonprodbucket-1mi4d3rdxq50m
    steps: 
      - name: checkout-code
        uses: actions/checkout@v2
      - name: configure-aws-cli
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS }}
          aws-region: us-east-1
      - name: setup-node-js
        uses: actions/setup-node@v2
        with: 
          node-version: 14
      - name: build state
        run: 
          npm ci
          npm run build
      - name: deploy files to bucket
        run: aws s3 cp public s3://${{ env.BUCKET_NAME }} --recursive --acl public-read
        
